<a href="https://colab.research.google.com/github/subha1625/Machine-Learning/blob/main/NeuralNetwork_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [3]:
y=np.array([[1],[0],[1]])

In [4]:
y

array([[1],
       [0],
       [1]])

In [5]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [6]:
def derivative_sigmoid(x):
  return x*(1-x)

In [7]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [8]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [11]:
for i in range(epoch):
    # Forward pass
    hidden_input = np.dot(x, wh) + bh
    hidden_activation = sigmoid(hidden_input)
    output_layer = np.dot(hidden_activation, wo) + bo
    output = sigmoid(output_layer)

    # Backward pass
    E = y - output
    slope_output = derivative_sigmoid(output)
    slope_hidden = derivative_sigmoid(hidden_activation)
    d_output = E * slope_output
    error_hidden = d_output.dot(wo.T)
    d_hidden = error_hidden * slope_hidden

    # Update weights and biases
    wo += hidden_activation.T.dot(d_output) * lr
    bo += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += x.T.dot(d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

In [12]:
output

array([[0.97162289],
       [0.03905493],
       [0.9772142 ]])